---
- name: Creating complex users
  hosts: all
  vars_files:
    - user_list.yml
  tasks:
    - name: Creating users
      vars:
        - password: "{{ lookup('password','password-' + item.name + 'length=6 chars=digits encrypt=sha512_crypt' ) }}"
      ansible.builtin.user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        password: "{{ password }}"
        comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
      loop: "{{ users }}"
